version: "3.7"
services:
    
    db:
        image: mariadb:1.2.3
        container_name: pet-db
        volumes:
            - type: volume
              source: db-data
              target: /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=5tgb6yhn
            - MYSQL_DATABASE=pet_db
            - MYSQL_USER=pet_user
            - MYSQL_PASSWORD=5tgb6yhn
        restart: always
    api:
        depends_on: 
            - db
        build: ./api
        container_name: pet-api
        volumes:
            - type: volume
              source: static-data
              target: /statics
        environment:
            - DB_DEBUG=False
            - DB_NAME=pet_db
            - DB_USER=pet_user
            - DB_PASS=5tgb6yhn
            - DB_HOST=pet-db
            - DB_PORT=3306
            - API_DEBUG=True
            - API_HOSTS=pet-api,localhost
            - API_SECRET="${API_SECRET}"
        ports:
            - "8001:8000"
        restart: always
    proxy:
        depends_on: 
            - api
        build: ./proxy
        container_name: pet-proxy
        volumes:
            - type: volume
              source: proxy-data
              target: /certs
              read_only: true
        ports: 
            - "8000:8000"
        restart: always

networks:
    default:
        driver: bridge
        name: pet-net

volumes:
    db-data:
        name: db-data
    proxy-data:
        external: true
        name: proxy-data

