# Generated by Django 2.2 on 2019-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parameters',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
