# Generated by Django 2.1.2 on 2019-06-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_previous',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='job_next', to='rest.Job'),
        ),
    ]
