# Generated by Django 2.2 on 2019-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20190421_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='exit_code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
